Repository fusionjs/fusionjs, pull requests merged in 2018-11, with the labels that each got.

#192 Upgrade dependencies and createContext typing
  package.json
  src/__tests__/client.browser.js
  src/__tests__/hoc.node.js
  src/__tests__/injector.node.js
  src/__tests__/plugin.js
  src/__tests__/render.js
  src/__tests__/server.node.js
  src/async/__tests__/__browser__/prepare-render.browser.js
  src/async/__tests__/__node__/context.node.js
  src/async/__tests__/__node__/prepare-context.node.js
  src/async/__tests__/__node__/prepare-render.node.js
  src/async/__tests__/__node__/split.node.js
  src/async/middleware.js
  src/async/prepare-provider.js
  src/async/prepare.js
  src/async/prepared.js
  src/async/split.js
  src/injector.js
  src/plugin.js
  yarn.lock
Labels: bugfix, dependencies, greenkeeping

#193 Release v1.3.3-0
  package.json
Labels: prerelease, release

#195 Release v1.3.3
  package.json
Labels: release

#196 Fix types
  package.json
  src/plugin.js
  yarn.lock
Labels: bugfix

#197 Release v1.3.4-0
  package.json
Labels: release

#198 Release v1.3.4
  package.json
Labels: release

#201 Upgrade dependencies
  package.json
  yarn.lock
Labels: greenkeeping
