Repository fusionjs/fusionjs, pull requests merged in 2018-10, with the labels that each got.

#174 Release v1.3.0
  package.json
Labels: release

#175 Fix flow release verification errors
  .flowconfig
  package.json
  src/__tests__/injector.node.js
  yarn.lock
Labels: greenkeeping

#178 Upgrade dependency versions
  package.json
  yarn.lock
Labels: greenkeeping

#181 Fix warning `Can't call setState on a component that is not yet mounted`
  src/async/__tests__/__node__/prepare-render.node.js
  src/async/prepare.js
Labels: bugfix

#182 Release v1.3.1-1
  package.json
Labels: release

#190 Validate that async component contains a default export
  src/async/split.js
Labels: feature

#188 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#191 Release v1.3.2
  package.json
Labels: release
