Repository fusionjs/fusionjs, pull requests merged in 2018-12, with the labels that each got.

#204 Clarify `prepare` use case
  README.md
Labels: docs

#205 Fix flow issue with component name
  src/hoc.js
Labels: bugfix

#206 Release v1.3.5
  package.json
Labels: release
