Repository fusionjs/fusionjs, pull requests merged in 2018-08, with the labels that each got.

#143 Call componentWillUnmount in the browser
  src/async/__tests__/index.browser.js
  src/async/prepare.js
Labels: bugfix

#141 Fix flow syntax highlighting in README.md
  README.md
Labels: docs

#149 Support using UNSAFE_componentWillMount
  package.json
  src/async/__tests__/__node__/prepare-render.node.js
  src/async/prepare.js
  src/async/prepared.js
  yarn.lock
Labels: greenkeeping

#153 Add support for getDerivedStateFromProps
  README.md
  src/async/__tests__/__node__/prepare-render.node.js
  src/async/prepare.js
Labels: bugfix

#155 Release v1.2.1
  package.json
Labels: release

#160 Revert "Call componentWillUnmount in the browser"
  src/async/__tests__/index.browser.js
  src/async/prepare.js
Labels: bugfix
