Repository fusionjs/fusionjs, pull requests merged in 2019-05, with the labels that each got.

#376 Add CTX to browser errors to assist with debugging
  fusion-plugin-error-handling/src/__tests__/index.node.js
  fusion-plugin-error-handling/src/server.js
  fusion-plugin-error-handling/src/types.js
Labels: bugfix

#381 Update usage of deprecated API
  fusion-cli/build/plugins/child-compilation-plugin.js
Labels: greenkeeping

#385 Handle non-Error promise rejections
  fusion-plugin-error-handling/fixtures/unhandled-rejection-non-error.js
  fusion-plugin-error-handling/src/__tests__/index.node.js
  fusion-plugin-error-handling/src/server.js
Labels: bugfix

#386 Resolve Flow complaints in fusion-plugin-apollo
  fusion-plugin-apollo/flow-typed/npm/redux_v4.x.x.js
Labels: bugfix

#388 Resolve Flow complaints in fusion-plugin-jwt
  fusion-plugin-jwt/flow-typed/npm/node-fetch_v1.x.x.js
Labels: bugfix

#390 Remove babel polyfill, use core-js and regenerator-runtime directly
  fusion-cli/build/get-babel-config.js
  fusion-cli/entries/client-public-path.js
  fusion-cli/package.json
Labels: greenkeeping

#391 Add throwing an error when ServiceContext.Provider wasn't registered
  fusion-react/src/context.js
Labels: bugfix

#389 Pass token into ProvidedHOC
  fusion-plugin-universal-events-react/src/hoc.js
Labels: greenkeeping

#392 Remove legacy context from styletron plugin
  .buildkite/bootstrap.sh
  docs/migrations/00392.md
  fusion-plugin-styletron-react/src/browser.js
  fusion-plugin-styletron-react/src/legacy-provider.js
  fusion-plugin-styletron-react/src/server.js
Labels: breaking, docs

#400 Update create-fusion-app scaffold
  create-fusion-app/bin/cli.js
  create-fusion-app/templates/basic/content/package.json
  create-fusion-app/tests/test.js
Labels: greenkeeping

#404 Update libdef files to resolve remaining Flow complaints
  fusion-plugin-react-router/flow-typed/npm/history_v4.9.x.js
  fusion-plugin-react-router/flow-typed/npm/prop-types_v15.x.x.js
  fusion-plugin-react-router/flow-typed/npm/react-router-dom_v4.x.x.js
  fusion-plugin-react-router/src/types.js
Labels: bugfix

#405 Resolve Flow complaints in fusion-cli
  fusion-cli/.flowconfig
  fusion-cli/flow-typed/npm/react-router-dom_v4.x.x.js
Labels: bugfix

#406 Make README better
  README.md
Labels: docs

#408 Revert #406
  README.md
Labels: docs

#399 Use hooks in fusion-plugin-font-loader-react (take 2)
  common/config/rush/yarn.lock
  fusion-plugin-font-loader-react/docs/migrations/00399.md
  fusion-plugin-font-loader-react/package.json
  fusion-plugin-font-loader-react/src/plugin.js
  fusion-plugin-font-loader-react/src/with-font-loading.js
Labels: breaking, docs

#409 Make README better
  README.md
Labels: docs

#426 Add HTML 'lang' attribute for improved i18n accessibility
  fusion-plugin-i18n/src/__tests__/index.node.js
  fusion-plugin-i18n/src/node.js
Labels: bugfix

#420 Use scoped emitter when possible to emit browser stats
  fusion-plugin-browser-performance-emitter/src/server.js
Labels: bugfix

#397 Remove legacy context, refactor HOC in fusion-plugin-rpc-redux-react
  fusion-plugin-rpc-redux-react/.cuprc.js
  fusion-plugin-rpc-redux-react/.gitignore
  fusion-plugin-rpc-redux-react/README.md
  fusion-plugin-rpc-redux-react/docs/migrations/00397.md
  fusion-plugin-rpc-redux-react/flow-typed/tape-cup_v4.x.x.js
  fusion-plugin-rpc-redux-react/package.json
  fusion-plugin-rpc-redux-react/src/__tests__/index.browser.js
  fusion-plugin-rpc-redux-react/src/__tests__/index.node.js
  fusion-plugin-rpc-redux-react/src/__tests__/interface.js
  fusion-plugin-rpc-redux-react/src/hoc.js
  fusion-plugin-rpc-redux-react/src/plugin.js
  fusion-plugin-rpc-redux-react/test/browser.test.js
  fusion-plugin-rpc-redux-react/test/fixture/e2e.test.js
  fusion-plugin-rpc-redux-react/test/fixture/src/main.js
  fusion-plugin-rpc-redux-react/test/fixture/src/reducers/user.js
  fusion-plugin-rpc-redux-react/test/fixture/src/redux.js
  fusion-plugin-rpc-redux-react/test/fixture/src/root.js
  fusion-plugin-rpc-redux-react/test/fixture/src/rpc/index.js
  fusion-plugin-rpc-redux-react/test/interface.test.js
  fusion-plugin-rpc-redux-react/test/node.test.js
  fusion-plugin-rpc-redux-react/test/utils.js
Labels: breaking, docs

#403 Add a tree shaking test that involves the use of Flow types
  fusion-cli/test/e2e/tree-shaking-flow/fixture/.fusionrc.js
  fusion-cli/test/e2e/tree-shaking-flow/fixture/.gitignore
  fusion-cli/test/e2e/tree-shaking-flow/fixture/node_modules/fixture-pkg/dist/index.js
  fusion-cli/test/e2e/tree-shaking-flow/fixture/node_modules/fixture-pkg/dist/index.js.flow
  fusion-cli/test/e2e/tree-shaking-flow/fixture/node_modules/fixture-pkg/dist/index.js.map
  fusion-cli/test/e2e/tree-shaking-flow/fixture/node_modules/fixture-pkg/package.json
  fusion-cli/test/e2e/tree-shaking-flow/fixture/node_modules/fixture-pkg/src/index.js
  fusion-cli/test/e2e/tree-shaking-flow/fixture/node_modules/fixture-pkg/src/unused.js
  fusion-cli/test/e2e/tree-shaking-flow/fixture/node_modules/fixture-pkg/src/used.js
  fusion-cli/test/e2e/tree-shaking-flow/fixture/src/main.js
  fusion-cli/test/e2e/tree-shaking-flow/fixture/src/unused2.js
  fusion-cli/test/e2e/tree-shaking-flow/fixture/src/used2.js
  fusion-cli/test/e2e/tree-shaking-flow/fixture/src/user-code.js
  fusion-cli/test/e2e/tree-shaking-flow/test.js
Labels: bugfix

#440 Add logic for limiting the number of events sent in each batch
  fusion-plugin-universal-events/src/__tests__/test.browser.js
  fusion-plugin-universal-events/src/browser.js
  fusion-plugin-universal-events/src/storage/__tests__/storage-test.browser.js
  fusion-plugin-universal-events/src/storage/in-memory.js
  fusion-plugin-universal-events/src/storage/local-storage.js
  fusion-plugin-universal-events/src/storage/split.js
  fusion-plugin-universal-events/src/types.js
Labels: bugfix
