Repository fusionjs/fusionjs, pull requests merged in 2019-04, with the labels that each got.

#242 Add useService hook and modern Context
  README.md
  src/__tests__/context.node.js
  src/context.js
  src/index.js
Labels: feature

#243 Pass context to render function
  README.md
  src/__tests__/render.js
  src/index.js
Labels: bugfix

#241 Fix missing import in Provider/HOC example
  README.md
Labels: docs

#245 Refactor context usage
  README.md
  package.json
  src/__tests__/context.node.js
  src/__tests__/hoc.node.js
  src/__tests__/injector.node.js
  src/context.js
  src/hoc.js
  src/index.js
  src/injector.js
  yarn.lock
Labels: docs, feature, refactor
