Repository fusionjs/fusionjs, pull requests merged in 2019-06, with the labels that each got.

#418 Add GetDataFromTreeToken
  fusion-plugin-apollo/README.md
  fusion-plugin-apollo/src/plugin.js
  fusion-plugin-apollo/src/server.js
  fusion-plugin-apollo/src/tokens.js
Labels: docs

#439 Move ServiceContext Provider to root
  fusion-react/src/context.js
  fusion-react/src/index.js
Labels: bugfix

#434 Export relevant types directly from fusion-plugin-universal-events-react
  fusion-plugin-universal-events-react/src/index.js
Labels: feature

#455 Add RPC stats from the browser
  fusion-plugin-rpc-redux-react/test/browser.test.js
  fusion-plugin-rpc-redux-react/test/node.test.js
  fusion-plugin-rpc/src/__tests__/create-mock-emitter.js
  fusion-plugin-rpc/src/__tests__/index.browser.js
  fusion-plugin-rpc/src/__tests__/index.node.js
  fusion-plugin-rpc/src/__tests__/test-mock.js
  fusion-plugin-rpc/src/browser.js
  fusion-plugin-rpc/src/mock.js
  fusion-plugin-rpc/src/server.js
  fusion-plugin-rpc/src/types.js
Labels: breaking

#463 Fix inconsistency between Flow and Prettier
  eslint-config-fusion/index.js
Labels: bugfix

#443 RFC: Support asynchronous .provides
  rfcs/text/0003-make-provides-async.md
Labels: rfc

#462 Support dynamic translations
  fusion-cli/build/babel-plugins/babel-plugin-i18n/index.js
  fusion-cli/build/babel-plugins/babel-plugin-i18n/test/index.test.js
  fusion-cli/test/e2e/split-translations/fixture/src/hocTranslation.js
  fusion-cli/test/e2e/split-translations/fixture/src/hookTranslation.js
  fusion-cli/test/e2e/split-translations/fixture/src/root.js
  fusion-cli/test/e2e/split-translations/fixture/translations/en-US.json
  fusion-cli/test/e2e/split-translations/test.js
  fusion-plugin-i18n-react/README.md
  fusion-plugin-i18n-react/src/__tests__/__snapshots__/use-translations.test.browser.js.snap
  fusion-plugin-i18n-react/src/__tests__/use-translations.test.browser.js
  fusion-plugin-i18n-react/src/index.js
  fusion-plugin-i18n-react/src/use-translations.js
  fusion-plugin-i18n/src/__tests__/index.browser.js
  fusion-plugin-i18n/src/__tests__/index.node.js
  fusion-plugin-i18n/src/browser.js
  fusion-plugin-i18n/src/node.js
Labels: feature

#456 Add config to fusion-plugin-rpc for customizing api path
  fusion-plugin-rpc/README.md
  fusion-plugin-rpc/src/__tests__/index.browser.js
  fusion-plugin-rpc/src/__tests__/index.node.js
  fusion-plugin-rpc/src/browser.js
  fusion-plugin-rpc/src/index.js
  fusion-plugin-rpc/src/server.js
  fusion-plugin-rpc/src/tokens.js
  fusion-plugin-rpc/src/types.js
  fusion-plugin-rpc/src/utils.js
Labels: feature

#394 Add web app manifest plugin
  common/config/rush/yarn.lock
  fusion-cli/build/plugins/client-chunk-metadata-state-hydrator-plugin.js
  fusion-cli/plugins/ssr-plugin.js
  fusion-core/src/base-app.js
  fusion-core/src/get-env.js
  fusion-core/src/index.js
  fusion-core/src/plugins/ssr.js
  fusion-plugin-csrf-protection/src/index.js
  fusion-plugin-error-handling/src/index.js
  fusion-plugin-font-loader-react/src/generate-preload-links.js
  fusion-plugin-introspect/src/index.js
  fusion-plugin-jwt/src/index.js
  fusion-plugin-react-helmet-async/src/index.js
  fusion-plugin-react-redux/src/fixtures/success/flow-success.js
  fusion-plugin-react-redux/src/index.js
  fusion-plugin-rpc/src/index.js
  fusion-plugin-service-worker/src/index.js
  fusion-plugin-styletron-react/src/index.js
  fusion-plugin-universal-logger/src/index.js
  fusion-plugin-web-app-manifest/.buildkite/browserTests
  fusion-plugin-web-app-manifest/.buildkite/nodeTests
  fusion-plugin-web-app-manifest/.cuprc.js
  fusion-plugin-web-app-manifest/.eslintrc.js
  fusion-plugin-web-app-manifest/.flowconfig
  fusion-plugin-web-app-manifest/.gitignore
  fusion-plugin-web-app-manifest/LICENSE
  fusion-plugin-web-app-manifest/README.md
  fusion-plugin-web-app-manifest/flow-typed/globals.js
  fusion-plugin-web-app-manifest/package.json
  fusion-plugin-web-app-manifest/renovate.json
  fusion-plugin-web-app-manifest/src/__tests__/index.browser.js
  fusion-plugin-web-app-manifest/src/__tests__/index.node.js
  fusion-plugin-web-app-manifest/src/browser.js
  fusion-plugin-web-app-manifest/src/index.js
  fusion-plugin-web-app-manifest/src/server.js
  fusion-plugin-web-app-manifest/src/tokens.js
  fusion-plugin-web-app-manifest/src/types.js
  fusion-react/src/index.js
  rush.json
Labels: docs, feature

#471 Fix support for React Portals
  common/config/rush/yarn.lock
  fusion-react/package.json
  fusion-react/src/async/__tests__/prepare-render.browser.js
  fusion-react/src/async/prepare.js
Labels: bugfix

#477 Fix client url in context [fusion-core]
  fusion-core/src/client-app.js
Labels: bugfix

#472 Add RFC for enhanced Flow support in the monorepo
  rfcs/text/0004-support-flow-in-monorepo.md
Labels: rfc

#507 Audit libdefs and update to @latest
  flow-typed/history_v4.9.x.js
  flow-typed/koa_v2.x.x.js
  flow-typed/locale.js
  flow-typed/npm/apollo-client_v2.x.x.js
  flow-typed/npm/jest_v24.x.x.js
  flow-typed/npm/jsonwebtoken_v8.1.x.js
  flow-typed/npm/jsonwebtoken_v8.3.x.js
  flow-typed/npm/prop-types_v15.x.x.js
  flow-typed/npm/redux_v4.x.x.js
  flow-typed/npm/winston_v3.x.x.js
  flow-typed/react-router-dom_v4.x.x.js
  flow-typed/tape-cup_v4.x.x.js
  flow-typed/winston_v3.x.x.js
  fusion-plugin-universal-logger/src/tokens.js
Labels: bugfix
