Repository fusionjs/fusionjs, pull requests merged in 2019-02, with the labels that each got.

#229 Upgrade flow-bin and fusion-core in lockstep
  package.json
  yarn.lock
Labels: greenkeeping

#231 Release v2.0.0-alpha.0
  package.json
Labels: release

#232 Release v2.0.0-alpha.1
  package.json
Labels: release

#233 Release v2.0.0-alpha.2
  package.json
Labels: release

#227 Update async rendering for React 16
  README.md
  docs/migrations/00227.md
  package.json
  src/async/__tests__/__browser__/prepare-render.browser.js
  src/async/__tests__/__node__/prepare-context.node.js
  src/async/__tests__/__node__/prepare-render.node.js
  src/async/__tests__/__node__/split.node.js
  src/async/__tests__/index.browser.js
  src/async/constants.js
  src/async/dispatched.js
  src/async/flowtests/flowtests.js
  src/async/index.js
  src/async/prepare.js
  src/async/prepared.js
  src/async/split.js
  src/async/traverse-exclude.js
  src/async/utils/__tests__/isReactCompositeComponent.node.js
  src/async/utils/__tests__/isReactFunctionalComponent.node.js
  src/async/utils/isReactCompositeComponent.js
  src/async/utils/isReactFunctionalComponent.js
  src/index.js
  yarn.lock
Labels: breaking
